FROM nginx:stable

# Use either the full config or the simple one (comment one line and uncomment the other)
COPY ./config/nginx.conf /etc/nginx/nginx.conf
# COPY ./config/simple.conf /etc/nginx/nginx.conf

EXPOSE 80 5000